### ISSUE TITLE
Database init vs schema mismatch

### ISSUE THREAD

**Issue by sickify1** [lejacobroy/Tidalrr#1]
Trying to give this a spin, but have a few issues. The first is some errors from the database __init__.py, it looks like Insert statement on line 35 of __init__.py uses a column named checkExists, but in the schema file it is checkExist.
And then line 36 should be usePlaylistFolder instead of unePlaylistFolder.

Not sure if it should be a separate issue, but after correcting the typos and trying to start I get the following:
`Traceback (most recent call last):
  File "/home/sickify/Docker/Tidalrr/app.py", line 12, in <module>
    from runWebServer import *
  File "/home/sickify/Docker/Tidalrr/runWebServer.py", line 12, in <module>
    from tidalrr.webserver import *
  File "/home/sickify/Docker/Tidalrr/tidalrr/webserver/__init__.py", line 10, in <module>
    from tidalrr.workers import *
  File "/home/sickify/Docker/Tidalrr/tidalrr/workers/__init__.py", line 13, in <module>
    from tidalrr.tidal import *
  File "/home/sickify/Docker/Tidalrr/tidalrr/tidal.py", line 698, in <module>
    TIDAL_API = TidalAPI()
  File "/home/sickify/Docker/Tidalrr/tidalrr/tidal.py", line 283, in __init__
    self.key.clientId = '7m7Ap0JC9j1cOM3n'
AttributeError: 'list' object has no attribute 'clientId'
`
I'm a python beginner, but it looks like getItems() on line 282 does not have anything to do with the keys. I tried it with __get__() instead, but unsure what should go in as a path.

**Comment by sickify1** [comment]
Both these issues are fixed with the latest commit.

Looks like I was wildly off-base with the getItems() part.
