### ISSUE TITLE
fails to start automated scanning and downloading

### ISSUE THREAD

**Issue by styx-techno** [lejacobroy/Tidalrr#20]
hey there, I have tdallr installed on my server in a container and I noticed that the automated/scheduled scan and download doesnt work. I looked inside the pod logs and found this:
2024-05-06 08:03:20.619785+02:00Starting tidalrr app
2024-05-06 08:03:20.648044+02:00Scans are scheduled
2024-05-06 08:03:20.648111+02:00Downloads are scheduled
2024-05-06 08:03:23.813573+02:00Non-Empty Access Token, logging in
2024-05-06 08:03:24.335646+02:00Starting web server
2024-05-06 08:03:24.381861+02:00* Serving Flask app 'tidalrr.webserver'
2024-05-06 08:03:24.381958+02:00* Debug mode: off
2024-05-06 08:03:24.383183+02:00WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
2024-05-06 08:03:24.383219+02:00* Running on all addresses (0.0.0.0)
2024-05-06 08:03:24.383227+02:00* Running on http://127.0.0.1:3001
2024-05-06 08:03:24.383234+02:00* Running on http://172.16.8.94:3001
2024-05-06 08:03:24.383401+02:00Press CTRL+C to quit
2024-05-06 09:00:00.289468+02:002024-05-06 07:00:00 Starting scans
2024-05-06 09:00:00.299524+02:00LOG: Running job "startScans"
2024-05-06 09:00:00.302845+02:002024-05-06 07:00:00 startScans
2024-05-06 09:00:00.307662+02:00Non-Empty Access Token, logging in
2024-05-06 09:00:00.783019+02:00tidalrrStart
2024-05-06 09:00:00.783186+02:00Process Process-2:1:
2024-05-06 09:00:00.788145+02:00Traceback (most recent call last):
2024-05-06 09:00:00.789267+02:00File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-05-06 09:00:00.789358+02:00self.run()
2024-05-06 09:00:00.789391+02:00File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-05-06 09:00:00.789418+02:00self._target(*self._args, **self._kwargs)
2024-05-06 09:00:00.789446+02:00File "/app/tidalrr/workers/__init__.py", line 25, in wrapper
2024-05-06 09:00:00.789472+02:00result = func(*args, **kwargs)
2024-05-06 09:00:00.789515+02:00^^^^^^^^^^^^^^^^^^^^^
2024-05-06 09:00:00.789570+02:00File "/app/runSchedule.py", line 31, in startScans
2024-05-06 09:00:00.789601+02:00scanQueuedArtists()
2024-05-06 09:00:00.789628+02:00TypeError: 'module' object is not callable
2024-05-06 19:39:46.475528+02:00Non-Empty Access Token, logging in
2024-05-06 19:39:47.064995+02:002024-05-06T19:39:47.064995749+02:00

manually, everything works. Did I miss something in the config or the requirements?

**Comment by lejacobroy** [comment]
Do you use the official docker container?

**Comment by styx-techno** [comment]
as far as I can tell, yes: 
![grafik](https://github.com/lejacobroy/Tidalrr/assets/5517989/f2ff04aa-2e41-431a-9d0d-a473a4272dfa)

**Comment by styx-techno** [comment]
I'm currently trying to recreate the issue in a local docker container, to verify that it is indeed hardware/platform agnostic. There is a slight chance that it may be my server that is the cuplrit, but if it stays the same on my docker desktop environment its in the code

**Comment by styx-techno** [comment]
I can recreate the issue in docker, so its in the code.
![grafik](https://github.com/lejacobroy/Tidalrr/assets/5517989/f2543770-f25a-4fe8-b43b-9f16e31e80cc)

**Comment by zaheria985** [comment]
I am currently having this same issue

**Comment by lejacobroy** [comment]
I converted all the imports to named imports (instead of wildcards).
It fixed the issue on my end, and it's saner.

Please pull the latest docker image and confirm that it's fixed for you too!
https://hub.docker.com/layers/jacobroyquebec/tidalrr/latest/images/sha256-882caf2399409423fc2dd20f08be11f64f0c5e74a05635796886c2a5087cc440?context=repo

**Comment by styx-techno** [comment]
seems to be fixed now, I'll deploy it to my server and monitor it over the next clouple of days!
