### ISSUE TITLE
Error on boot - no web access

### ISSUE THREAD

**Issue by mangocat1** [lejacobroy/Tidalrr#5]
I'm getting this error on boot. My Compose is below. I suspect this is a syntax issue.

2024-02-12 22:00:28 watchtower-1  | time="2024-02-13T05:00:28Z" level=info msg="Watchtower 1.7.1"
2024-02-12 22:00:29 tidalrr       | Starting tidalrr app
2024-02-12 22:00:28 watchtower-1  | time="2024-02-13T05:00:28Z" level=info msg="Using no notifications"
2024-02-12 22:00:28 watchtower-1  | time="2024-02-13T05:00:28Z" level=info msg="Checking all containers (except explicitly disabled with label)"
2024-02-12 22:00:29 tidalrr       | Scans are scheduled
2024-02-12 22:00:29 tidalrr       | Downloads are scheduled
2024-02-12 22:00:28 watchtower-1  | time="2024-02-13T05:00:28Z" level=info msg="Scheduling first run: 2024-02-14 05:00:28 +0000 UTC"
2024-02-12 22:00:29 tidalrr       | Process Process-1:
2024-02-12 22:00:28 watchtower-1  | time="2024-02-13T05:00:28Z" level=info msg="Note that the first check will be performed in 23 hours, 59 minutes, 59 seconds"
2024-02-12 22:00:29 tidalrr       | Traceback (most recent call last):
2024-02-12 22:00:29 tidalrr       |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
2024-02-12 22:00:29 tidalrr       |     self.run()
2024-02-12 22:00:29 tidalrr       |   File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
2024-02-12 22:00:29 tidalrr       |     self._target(*self._args, **self._kwargs)
2024-02-12 22:00:29 tidalrr       |   File "/app/tidalrr/webserver/__init__.py", line 167, in webServer
2024-02-12 22:00:29 tidalrr       |     migration()
2024-02-12 22:00:29 tidalrr       |   File "/app/tidalrr/database/__init__.py", line 51, in migration
2024-02-12 22:00:29 tidalrr       |     conn.execute("ALTER TABLE tidal_artists \
2024-02-12 22:00:29 tidalrr       | sqlite3.OperationalError: no such column: "queued"

version: '3.7'
services:
  tidalrr:
    container_name: tidalrr
    image: jacobroyquebec/tidalrr 
    restart: always
    environment:
      - TZ=America/Denver
      - PUID=501
      - PGID=501
    ports:
      - 3001:3001
    volumes:
      - "C:/ProgramData/Lidarr:/app/tidalrr/database/config"
      - "G:/Torrent/Downloading:/app/download"
      - "G:/Torrent/Downloaded:/app/import"
      - "F:/Music/:/path/to/lidarr/folders"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

**Comment by sickify1** [comment]
I'm wondering if you modify line 110 of __init__.py in the database folder from a value of 1 to 4, then delete the database file and start the container again, if it might fix this.

**Comment by mangocat1** [comment]
That did it. Thanks for the direction!

**Comment by mangocat1** [comment]
Thanks! that did it!
